import * as Joi from 'joi';

export const configSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  PORT: Joi.number().default(3000),
  DATABASE_URL: Joi.string().required(),
  REDIS_HOST: Joi.string().optional().allow(''),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().optional().allow(''),
  REDIS_URL: Joi.string().optional().allow(''),
  API_BASE_URL: Joi.string().required(),
  APP_BASE_URL: Joi.string().optional().allow(''),
  CORS_ORIGIN: Joi.string().optional().allow(''),
  CORS_ORIGINS: Joi.string().optional().allow(''),
  JWT_SECRET: Joi.string().required(),
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: Joi.string().default('15m'),
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: Joi.string().default('30d'),
  JWT_REFRESH_TOKEN_EXPIRATION_TIME_MS: Joi.number().default(2592000000),
  JWT_REFRESH_SECRET: Joi.string().optional().allow(''),
  OPENAI_API_KEY: Joi.string().required(),
  USDA_API_KEY: Joi.string().optional().allow(''),
  FDC_API_BASE: Joi.string().optional().default('https://api.nal.usda.gov/fdc'),
  FDC_API_KEY: Joi.string().optional().allow(''),
  FDC_CACHE_TTL_SECONDS: Joi.number().optional().default(86400),
  NUTRITION_PROVIDER: Joi.string().valid('hybrid', 'openai', 'usda').default('hybrid'),
  NUTRITION_FEATURE_FALLBACK: Joi.boolean().default(true),
  NUTRITION_FEATURE_ENABLED: Joi.boolean().default(true),
  FREE_DAILY_ANALYSES: Joi.number().integer().min(0).default(3),
  PRO_DAILY_ANALYSES: Joi.number().integer().min(0).default(25),
  DISABLE_LIMITS: Joi.boolean().default(false),
  ADMIN_BYPASS_LIMITS: Joi.boolean().default(false),
  ASSISTANT_FLOWS_ENABLED: Joi.boolean().default(true),
  SENDGRID_API_KEY: Joi.string().optional().allow(''),
  MAIL_PROVIDER: Joi.string().valid('SMTP', 'SENDGRID').default('SMTP'),
  MAIL_FROM: Joi.string().optional().default('EatSense <timur.kamaraev@eatsense.ch>'),
  SMTP_HOST: Joi.string().optional().allow(''),
  SMTP_PORT: Joi.number().optional().default(465),
  SMTP_SECURE: Joi.boolean().optional().default(true),
  SMTP_USER: Joi.string().optional().allow(''),
  SMTP_PASS: Joi.string().optional().allow(''),
  MAIL_DISABLE: Joi.boolean().default(false),
  AUTH_DEV_IGNORE_MAIL_ERRORS: Joi.boolean().default(false),
  EXPO_ACCESS_TOKEN: Joi.string().optional().allow(''),
  NOTIFICATIONS_DAILY_DEFAULT_HOUR: Joi.number().optional().min(0).max(23).default(8),
  HEALTH_SCORE_WEIGHTS: Joi.string().optional().allow(''),
  CACHE_DEFAULT_TTL_SEC: Joi.number().optional().default(900),
  USDA_CACHE_TTL_SEC: Joi.number().optional().default(259200),
  ANALYSIS_CACHE_TTL_SEC: Joi.number().optional().default(86400),
  ARTICLES_FEED_CACHE_TTL_SEC: Joi.number().optional().default(900),
  ARTICLES_DETAIL_CACHE_TTL_SEC: Joi.number().optional().default(86400),
  ASSISTANT_SESSION_TTL_SEC: Joi.number().optional().default(1800),
  S3_ENDPOINT: Joi.string().optional().allow(''),
  S3_REGION: Joi.string().optional().allow(''),
  S3_BUCKET: Joi.string().optional().allow(''),
  S3_ACCESS_KEY_ID: Joi.string().optional().allow(''),
  S3_SECRET_ACCESS_KEY: Joi.string().optional().allow(''),
  S3_FORCE_PATH_STYLE: Joi.boolean().optional().default(true),
  // Apple In-App Purchase settings for Promotional Offers
  APPLE_IAP_KEY_ID: Joi.string().optional().allow(''),
  APPLE_IAP_ISSUER_ID: Joi.string().optional().allow(''),
  APPLE_IAP_KEY: Joi.string().optional().allow(''), // Contents of .p8 file
  APP_BUNDLE_ID: Joi.string().optional().default('ch.eatsense.app'),
  APPLE_BUNDLE_ID: Joi.string().optional().default('ch.eatsense.app'),
  // Medication push notifications (disabled by default, use local notifications)
  MEDICATION_PUSH_ENABLED: Joi.boolean().optional().default(false),
});