import { Controller, Get, Res, Header } from '@nestjs/common';
import { Response } from 'express';

/**
 * Serves the admin panel HTML at GET /admin
 * No JWT required — the panel itself authenticates via ADMIN_SECRET header
 */
@Controller('admin')
export class AdminPanelController {
  @Get()
  @Header('Content-Type', 'text/html')
  getAdminPanel(@Res() res: Response) {
    res.send(ADMIN_HTML);
  }
}

/* eslint-disable max-len */
const ADMIN_HTML = [
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
'<title>EatSense Admin Panel</title>',
'<style>',
':root{--bg:#0f1117;--surface:#1a1d27;--surface2:#22263a;--border:#2d3148;--text:#e4e8f7;--text2:#8b91a8;--primary:#6366f1;--primary-hover:#818cf8;--green:#22c55e;--green-bg:#22c55e22;--red:#ef4444;--red-bg:#ef444422;--yellow:#f59e0b;--yellow-bg:#f59e0b22;--blue:#3b82f6;--blue-bg:#3b82f622}',
'*{margin:0;padding:0;box-sizing:border-box}',
'body{font-family:-apple-system,BlinkMacSystemFont,"Inter","Segoe UI",sans-serif;background:var(--bg);color:var(--text);min-height:100vh}',
'#login-screen{display:flex;align-items:center;justify-content:center;min-height:100vh}',
'.login-card{background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:40px;width:380px;text-align:center}',
'.login-card h1{font-size:22px;margin-bottom:6px}',
'.login-card p{color:var(--text2);font-size:14px;margin-bottom:24px}',
'.login-card input{width:100%;padding:12px 16px;border-radius:10px;border:1px solid var(--border);background:var(--bg);color:var(--text);font-size:14px;margin-bottom:16px;outline:none}',
'.login-card input:focus{border-color:var(--primary)}',
'#app{display:none}',
'.topbar{background:var(--surface);border-bottom:1px solid var(--border);padding:14px 28px;display:flex;justify-content:space-between;align-items:center}',
'.topbar h1{font-size:18px;display:flex;align-items:center;gap:10px}',
'.topbar .dot{width:8px;height:8px;border-radius:50%;background:var(--green)}',
'.tabs{display:flex;gap:4px;padding:12px 28px 0;border-bottom:1px solid var(--border)}',
'.tab{padding:10px 18px;cursor:pointer;font-size:14px;font-weight:500;color:var(--text2);border-bottom:2px solid transparent;transition:all .15s}',
'.tab:hover{color:var(--text)}.tab.active{color:var(--primary);border-bottom-color:var(--primary)}',
'.content{padding:24px 28px;max-width:1200px;margin:0 auto}',
'.btn{padding:8px 16px;border-radius:8px;border:none;font-size:13px;font-weight:600;cursor:pointer;transition:all .15s}',
'.btn-primary{background:var(--primary);color:#fff}.btn-primary:hover{background:var(--primary-hover)}',
'.btn-green{background:var(--green-bg);color:var(--green);border:1px solid #22c55e44}.btn-green:hover{background:var(--green);color:#fff}',
'.btn-red{background:var(--red-bg);color:var(--red);border:1px solid #ef444444}.btn-red:hover{background:var(--red);color:#fff}',
'.btn-yellow{background:var(--yellow-bg);color:var(--yellow);border:1px solid #f59e0b44}.btn-yellow:hover{background:var(--yellow);color:#fff}',
'.btn-outline{background:transparent;color:var(--text2);border:1px solid var(--border)}.btn-outline:hover{color:var(--text);border-color:var(--text2)}',
'.btn-sm{padding:6px 12px;font-size:12px}.btn:disabled{opacity:.5;pointer-events:none}',
'.card{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:18px;margin-bottom:12px}',
'.card-header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px}',
'.card-title{font-size:15px;font-weight:600}.card-meta{font-size:12px;color:var(--text2);margin-top:4px}',
'.card-body{font-size:14px;color:var(--text2);line-height:1.6}',
'.card-actions{display:flex;gap:8px;margin-top:14px;flex-wrap:wrap}',
'.badge{display:inline-block;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:600}',
'.badge-pending{background:var(--yellow-bg);color:var(--yellow)}',
'.badge-votes{background:var(--blue-bg);color:var(--blue)}',
'.badge-diet{background:var(--green-bg);color:var(--green)}',
'.badge-lifestyle{background:var(--primary);color:#fff;opacity:.85}',
'.empty-state{text-align:center;padding:60px 20px;color:var(--text2)}.empty-state .icon{font-size:48px;margin-bottom:12px}',
'.stat-bar{display:flex;gap:16px;margin-bottom:24px;flex-wrap:wrap}',
'.stat{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:16px 20px;min-width:120px}',
'.stat-value{font-size:28px;font-weight:700}.stat-label{font-size:12px;color:var(--text2);margin-top:2px}',
'.report-content{background:var(--bg);border-radius:8px;padding:12px;margin-top:8px;font-size:13px;line-height:1.5}',
'.report-content .label{color:var(--text2);font-size:11px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:4px}',
'.filter-bar{display:flex;gap:8px;margin-bottom:18px}.filter-bar .btn.active{background:var(--primary);color:#fff;border-color:var(--primary)}',
'.toast{position:fixed;bottom:24px;right:24px;background:var(--surface2);border:1px solid var(--border);border-radius:10px;padding:12px 20px;font-size:14px;z-index:1000;animation:slideIn .3s ease}',
'@keyframes slideIn{from{transform:translateY(20px);opacity:0}to{transform:translateY(0);opacity:1}}',
'.loading{text-align:center;padding:40px;color:var(--text2)}',
'</style>',
'</head>',
'<body>',
'<div id="login-screen"><div class="login-card">',
'<h1>&#x1F34F; EatSense Admin</h1>',
'<p>Enter your admin secret to continue</p>',
'<input type="password" id="admin-secret" placeholder="Admin Secret" />',
'<button class="btn btn-primary" style="width:100%;padding:12px" id="login-btn">Sign In</button>',
'<p id="login-error" style="color:var(--red);margin-top:12px;display:none;font-size:13px"></p>',
'</div></div>',
'<div id="app">',
'<div class="topbar"><h1><span class="dot"></span> EatSense Admin</h1>',
'<div><button class="btn btn-outline btn-sm" id="logout-btn">Sign Out</button></div></div>',
'<div class="tabs">',
'<div class="tab active" data-tab="suggestions">Suggestions</div>',
'<div class="tab" data-tab="reports">Reports</div>',
'</div>',
'<div class="content">',
'<div id="tab-suggestions"><div class="stat-bar" id="suggestions-stats"></div><div id="suggestions-list"><div class="loading">Loading suggestions...</div></div></div>',
'<div id="tab-reports" style="display:none">',
'<div class="filter-bar" id="reports-filter">',
'<button class="btn btn-outline btn-sm active" data-status="">All</button>',
'<button class="btn btn-outline btn-sm" data-status="PENDING">Pending</button>',
'<button class="btn btn-outline btn-sm" data-status="RESOLVED">Resolved</button>',
'<button class="btn btn-outline btn-sm" data-status="DISMISSED">Dismissed</button>',
'</div>',
'<div class="stat-bar" id="reports-stats"></div><div id="reports-list"><div class="loading">Loading reports...</div></div>',
'</div>',
'</div></div>',
'<script>',
'var API_URL=location.origin,ADMIN_SECRET="",currentFilter="";',
'',
'document.getElementById("login-btn").onclick=function(){',
'  var s=document.getElementById("admin-secret").value.trim();',
'  if(!s){showErr("Please enter Admin Secret");return}',
'  ADMIN_SECRET=s;',
'  api("/diets/suggestions/pending").then(function(){',
'    sessionStorage.setItem("as",s);showApp();',
'  }).catch(function(e){showErr("Invalid credentials: "+e.message)});',
'};',
'',
'document.getElementById("logout-btn").onclick=function(){sessionStorage.clear();location.reload()};',
'',
'function showErr(m){var e=document.getElementById("login-error");e.textContent=m;e.style.display="block"}',
'',
'function showApp(){',
'  document.getElementById("login-screen").style.display="none";',
'  document.getElementById("app").style.display="block";',
'  loadSuggestions();loadReports();',
'}',
'',
'(function(){var s=sessionStorage.getItem("as");if(s){ADMIN_SECRET=s;showApp()}})();',
'',
'function api(path,opts){',
'  opts=opts||{};',
'  return fetch(API_URL+path,{',
'    method:opts.method||"GET",',
'    headers:{"Content-Type":"application/json","x-admin-secret":ADMIN_SECRET},',
'    body:opts.body||undefined',
'  }).then(function(r){',
'    if(!r.ok)return r.json().catch(function(){return{}}).then(function(b){throw new Error(b.message||"HTTP "+r.status)});',
'    return r.json();',
'  });',
'}',
'',
'// Tabs',
'document.querySelectorAll(".tab").forEach(function(t){',
'  t.onclick=function(){',
'    document.querySelectorAll(".tab").forEach(function(x){x.classList.remove("active")});',
'    t.classList.add("active");',
'    document.getElementById("tab-suggestions").style.display=t.dataset.tab==="suggestions"?"block":"none";',
'    document.getElementById("tab-reports").style.display=t.dataset.tab==="reports"?"block":"none";',
'  };',
'});',
'',
'// Filter buttons',
'document.getElementById("reports-filter").onclick=function(e){',
'  var btn=e.target.closest("[data-status]");',
'  if(!btn)return;',
'  currentFilter=btn.dataset.status;',
'  document.querySelectorAll("#reports-filter .btn").forEach(function(b){b.classList.remove("active")});',
'  btn.classList.add("active");',
'  loadReports(currentFilter);',
'};',
'',
'// === SUGGESTIONS ===',
'function loadSuggestions(){',
'  api("/diets/suggestions/pending").then(renderSuggestions).catch(function(e){',
'    document.getElementById("suggestions-list").innerHTML="<div class=\\"empty-state\\">Error: "+esc(e.message)+"</div>";',
'  });',
'}',
'',
'function renderSuggestions(data){',
'  var s=document.getElementById("suggestions-stats"),l=document.getElementById("suggestions-list");',
'  var total=data.length,diets=data.filter(function(x){return x.type==="diet"}).length;',
'  var lifestyles=total-diets,votes=data.reduce(function(a,x){return a+x.votes},0);',
'  s.innerHTML=stat(total,"Pending")+stat(diets,"Diets")+stat(lifestyles,"Lifestyles")+stat(votes,"Total Votes");',
'  if(!total){l.innerHTML="<div class=\\"empty-state\\"><div class=\\"icon\\">&#x2705;</div>No pending suggestions</div>";return}',
'  l.innerHTML=data.map(function(x){',
'    var badge=x.type==="diet"?"badge-diet":"badge-lifestyle";',
'    return "<div class=\\"card\\"><div class=\\"card-header\\"><div>"',
'      +"<div class=\\"card-title\\">"+esc(x.name)+"</div>"',
'      +"<div class=\\"card-meta\\"><span class=\\"badge "+badge+"\\">"+x.type+"</span> "',
'      +"<span class=\\"badge badge-votes\\">"+x.votes+" vote"+(x.votes!==1?"s":"")+"</span>"',
'      +(x.createdAt?" <span>"+new Date(x.createdAt).toLocaleDateString()+"</span>":"")+"</div>"',
'      +"</div><span class=\\"badge badge-pending\\">pending</span></div>"',
'      +(x.description?"<div class=\\"card-body\\">"+esc(x.description)+"</div>":"")',
'      +"<div class=\\"card-actions\\">"',
'      +"<button class=\\"btn btn-green btn-sm\\" data-approve=\\""+x.id+"\\">Approve (6mo PRO)</button>"',
'      +"<button class=\\"btn btn-red btn-sm\\" data-reject=\\""+x.id+"\\">Reject</button>"',
'      +"</div></div>";',
'  }).join("");',
'}',
'',
'// Delegate suggestion clicks',
'document.getElementById("suggestions-list").onclick=function(e){',
'  var btn=e.target;',
'  if(btn.dataset.approve){',
'    if(!confirm("Approve this suggestion? The author will receive 6 months PRO."))return;',
'    api("/diets/suggestions/"+btn.dataset.approve+"/approve",{method:"PATCH"}).then(function(){',
'      toast("Suggestion approved! Author rewarded.");loadSuggestions();',
'    }).catch(function(e){toast("Error: "+e.message)});',
'  }',
'  if(btn.dataset.reject){',
'    if(!confirm("Reject this suggestion?"))return;',
'    api("/diets/suggestions/"+btn.dataset.reject+"/reject",{method:"PATCH"}).then(function(){',
'      toast("Suggestion rejected");loadSuggestions();',
'    }).catch(function(e){toast("Error: "+e.message)});',
'  }',
'};',
'',
'// === REPORTS ===',
'function loadReports(status){',
'  var q=status?"?status="+status:"";',
'  api("/community/admin/reports"+q).then(renderReports).catch(function(e){',
'    document.getElementById("reports-list").innerHTML="<div class=\\"empty-state\\">Error: "+esc(e.message)+"</div>";',
'  });',
'}',
'',
'function renderReports(data){',
'  var s=document.getElementById("reports-stats"),l=document.getElementById("reports-list");',
'  var pending=data.filter(function(r){return r.status==="PENDING"}).length;',
'  var resolved=data.filter(function(r){return r.status==="RESOLVED"}).length;',
'  var dismissed=data.filter(function(r){return r.status==="DISMISSED"}).length;',
'  s.innerHTML=stat(data.length,"Total")',
'    +"<div class=\\"stat\\"><div class=\\"stat-value\\" style=\\"color:var(--yellow)\\">"+pending+"</div><div class=\\"stat-label\\">Pending</div></div>"',
'    +"<div class=\\"stat\\"><div class=\\"stat-value\\" style=\\"color:var(--green)\\">"+resolved+"</div><div class=\\"stat-label\\">Resolved</div></div>"',
'    +"<div class=\\"stat\\"><div class=\\"stat-value\\" style=\\"color:var(--text2)\\">"+dismissed+"</div><div class=\\"stat-label\\">Dismissed</div></div>";',
'  if(!data.length){l.innerHTML="<div class=\\"empty-state\\"><div class=\\"icon\\">&#x1F389;</div>No reports found</div>";return}',
'  l.innerHTML=data.map(function(r){',
'    var name=userName(r.user),isPending=r.status==="PENDING",ch="";',
'    if(r.post){',
'      ch+="<div class=\\"report-content\\"><div class=\\"label\\">Reported Post (by "+esc(userName(r.post.author))+" in "+esc(r.post.group?r.post.group.name:"?")+")</div>"',
'        +"<div>"+esc((r.post.content||"").substring(0,300))+((r.post.content||"").length>300?"...":"")+"</div></div>";',
'    }',
'    if(r.comment){',
'      ch+="<div class=\\"report-content\\"><div class=\\"label\\">Reported Comment (by "+esc(userName(r.comment.author))+")</div>"',
'        +"<div>"+esc((r.comment.content||"").substring(0,300))+((r.comment.content||"").length>300?"...":"")+"</div></div>";',
'    }',
'    var actions="";',
'    if(isPending){',
'      actions="<div class=\\"card-actions\\">"',
'        +"<button class=\\"btn btn-green btn-sm\\" data-resolve=\\""+r.id+"\\" data-del=\\"false\\">Resolve (keep)</button>"',
'        +"<button class=\\"btn btn-red btn-sm\\" data-resolve=\\""+r.id+"\\" data-del=\\"true\\">Resolve &amp; Delete</button>"',
'        +"<button class=\\"btn btn-yellow btn-sm\\" data-dismiss=\\""+r.id+"\\">Dismiss</button>"',
'        +(r.post?"<button class=\\"btn btn-red btn-sm\\" data-delpost=\\""+r.post.id+"\\">Delete Post</button>":"")',
'        +(r.comment?"<button class=\\"btn btn-red btn-sm\\" data-delcomment=\\""+r.comment.id+"\\">Delete Comment</button>":"")',
'        +"</div>";',
'    }',
'    return "<div class=\\"card\\"><div class=\\"card-header\\"><div>"',
'      +"<div class=\\"card-title\\">Report from "+esc(name)+"</div>"',
'      +"<div class=\\"card-meta\\">Reason: <strong>"+esc(r.reason)+"</strong> &middot; "+new Date(r.createdAt).toLocaleString()+"</div>"',
'      +"</div><span class=\\"badge "+(isPending?"badge-pending":"")+"\\">"+r.status+"</span></div>"',
'      +ch+actions+"</div>";',
'  }).join("");',
'}',
'',
'// Delegate report clicks',
'document.getElementById("reports-list").onclick=function(e){',
'  var btn=e.target;',
'  if(btn.dataset.resolve){',
'    var del=btn.dataset.del==="true";',
'    if(!confirm(del?"Resolve and DELETE the reported content?":"Resolve this report (keep content)?"))return;',
'    api("/community/admin/reports/"+btn.dataset.resolve+"/resolve",{method:"PATCH",body:JSON.stringify({deleteContent:del})}).then(function(){',
'      toast(del?"Report resolved, content deleted":"Report resolved");loadReports(currentFilter);',
'    }).catch(function(e){toast("Error: "+e.message)});',
'  }',
'  if(btn.dataset.dismiss){',
'    if(!confirm("Dismiss this report?"))return;',
'    api("/community/admin/reports/"+btn.dataset.dismiss+"/dismiss",{method:"PATCH"}).then(function(){',
'      toast("Report dismissed");loadReports(currentFilter);',
'    }).catch(function(e){toast("Error: "+e.message)});',
'  }',
'  if(btn.dataset.delpost){',
'    if(!confirm("Delete this post permanently?"))return;',
'    api("/community/admin/posts/"+btn.dataset.delpost,{method:"DELETE"}).then(function(){',
'      toast("Post deleted");loadReports(currentFilter);',
'    }).catch(function(e){toast("Error: "+e.message)});',
'  }',
'  if(btn.dataset.delcomment){',
'    if(!confirm("Delete this comment permanently?"))return;',
'    api("/community/admin/comments/"+btn.dataset.delcomment,{method:"DELETE"}).then(function(){',
'      toast("Comment deleted");loadReports(currentFilter);',
'    }).catch(function(e){toast("Error: "+e.message)});',
'  }',
'};',
'',
'// Helpers',
'function userName(u){if(!u)return"Unknown";var p=u.userProfile;if(p&&p.firstName)return[p.firstName,p.lastName].filter(Boolean).join(" ");return u.email||"Unknown"}',
'function stat(v,label){return"<div class=\\"stat\\"><div class=\\"stat-value\\">"+v+"</div><div class=\\"stat-label\\">"+label+"</div></div>"}',
'function esc(s){if(!s)return"";var d=document.createElement("div");d.textContent=s;return d.innerHTML}',
'function toast(m){var el=document.createElement("div");el.className="toast";el.textContent=m;document.body.appendChild(el);setTimeout(function(){el.remove()},3500)}',
'</script>',
'</body></html>',
].join('\n');
